import * as React from "react";
import Head from "next/head";

import Layout from "@/components/layout";
import Header from "@/components/header";
import Container from "@/components/container";
import Button from "@/components/button";

import styles from "@/styles/Page.module.scss";

export default function Category() {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Container>
        <h1>Category Name</h1>

        <h2>Products</h2>

        <ul className={styles.products}>
          <li>
            <a href="#">
              <div className={styles.productImage}>Image</div>
              <h3 className={styles.productTitle}>Product Name</h3>
              <p className={styles.productPrice}>Product Price</p>
            </a>
            <p>
              <Button>Add to Cart</Button>
            </p>
          </li>
        </ul>
      </Container>
    </Layout>
  );
}
